spring.application.name=spring-postgres
spring.docker.compose.enabled=false


# handling db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=mburu
spring.datasource.password=mburu